site_name: Cotti's Bible
site_url: https://ncotti.github.io/docs/
docs_dir: docs

nav:
  - Home: index.md
  - About: about.md

  - MkDocs:
    - Introduction: mkdocs/index.md
    - Deployment: mkdocs/deployment.md

  - CI:
    - Introduction: ci/index.md
    - "Events: When workflows run": ci/events.md
    - "Jobs: What workflows do": ci/jobs.md
    - "Runners: Where workflows run": ci/runners.md

  - Build Systems:
    - Introduction: build_systems/index.md
    - Makefile: build_systems/makefile.md
    - CMake: build_systems/cmake.md

  - GDB:
    - Home: gdb/index.md
    - Tutorial: gdb/tutorial.md
    - Reference: gdb/reference.md
    - How-to Guides:
      - How to create a gdb script: gdb/how-to-guides/how_to_create_a_gdb_script.md

  - Linters:
    - Overview: linters/index.md
    - MarkDown: linters/markdown.md
    - Python: linters/python.md
    - C: linters/c.md
    - Latex: linters/latex.md

  - Docker:
    - Overview: docker/docker_index.md
    - Build images: docker/build_images.md
    - Run containers: docker/run_containers.md

  - Testing:
    - Gtest: testing/gtest.md

  - Git:
    - Best Practices: git/best_practices.md

  - Licencing:
    - Overview: licencing/licencing.md

  - Bare-metal:
    - Introduction: bare_metal/index.md
    - Interfaces:
      - Overview: bare_metal/interfaces/interfaces_overview.md
      - Jtag/Boundary-scan: bare_metal/interfaces/jtag.md
      - SWD: bare_metal/interfaces/swd.md
      - ST-Link: bare_metal/interfaces/stlink.md
      - USB-UART: bare_metal/interfaces/usb_uart.md
    - udev: bare_metal/udev.md
    - Arduino: bare_metal/arduino.md
    - OpenOCD: bare_metal/openocd.md


  - ARM Assembly:
    - Introduction: arm_assembly/index.md
    - Directives: arm_assembly/directives.md
    - Instructions: arm_assembly/instructions.md

  - PCB:
    - Common circuits: pcb/common_circuits.md

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Footnotes
  - footnotes

  # Annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences

  # Latex
  - pymdownx.arithmatex:
      generic: true

  # Mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Latex
extra_javascript:
- javascripts/mathjax.js
- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js