site_name: Cotti's Bible
site_url: https://ncotti.github.io/docs/
docs_dir: docs

nav:
  - Home: index.md
  - About: about.md

  - MkDocs:
    - Introduction: mkdocs/index.md
    - Deployment: mkdocs/deployment.md

  - CI:
    - Introduction: ci/index.md
    - "Events: When workflows run": ci/events.md
    - "Jobs: What workflows do": ci/jobs.md
    - "Runners: Where workflows run": ci/runners.md

  - Build Systems:
    - Introduction: build_systems/index.md
    - Makefile: build_systems/makefile.md
    - CMake: build_systems/cmake.md

  - GDB:
    - Home: gdb/index.md
    - Tutorial: gdb/tutorial.md
    - Reference: gdb/reference.md
    - How-to Guides:
      - How to create a gdb script: gdb/how-to-guides/how_to_create_a_gdb_script.md

  - Linters:
    - Overview: linters/index.md
    - MarkDown: linters/markdown.md

  - Docker:
    - Overview: docker/docker_index.md
    - Build images: docker/build_images.md
    - Run containers: docker/run_containers.md

  - Testing:
    - Gtest: testing/gtest.md

  - Git:
    - Best Practices: git/best_practices.md

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Footnotes
  - footnotes

  # Annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences

  # Mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format