name: "Using actions"
on: push
jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $(pwd)
          echo $(ls)

      - name: "Checkout repo"
        uses: actions/checkout@v5

      - run: |
          echo $(pwd)
          echo $(ls)
        

      - name: "Install Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: "Run Python script"
        run: python3 sample_script.py
