name: Run workflow if FORCE_CI is present
on: push
jobs:
  force_ci:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'FORCE_CI') }}
    steps:
      - run: echo "Hello world"